### ISSUE TITLE
[ERROR] NLP-Tools /keysentences 요청 실패 발생

### ISSUE THREAD

**Issue by playff** [osamhack2021/ai_web_RISKOUT_BTS#24]
- `/keysentences` 로 요청을 보내면 500 status 가 뜸.
- 아래 로그를 첨부함.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 243, in app
    is_coroutine=is_coroutine,
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 148, in serialize_response
    return jsonable_encoder(response_content)
  File "/usr/local/lib/python3.7/site-packages/fastapi/encoders.py", line 99, in jsonable_encoder
    sqlalchemy_safe=sqlalchemy_safe,
  File "/usr/local/lib/python3.7/site-packages/fastapi/encoders.py", line 116, in jsonable_encoder
    sqlalchemy_safe=sqlalchemy_safe,
  File "/usr/local/lib/python3.7/site-packages/fastapi/encoders.py", line 116, in jsonable_encoder
    sqlalchemy_safe=sqlalchemy_safe,
  File "/usr/local/lib/python3.7/site-packages/fastapi/encoders.py", line 144, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'numpy.int64' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
```

**Comment by playff** [comment]
[게시물](https://support.prodi.gy/t/typeerror-numpy-float32-object-is-not-iterable/2350)을 확인 후 기존 코드에 반환되는 `response`에 `jsonable` 하지 않은 numpy.int64 가 포함됨을 확인 따라서 형변환을 이용하여 `_keysentences`라는 변수를 만들어 반환
