### ISSUE TITLE
NLP 도커 빌드 실패 문제

### ISSUE THREAD

**Issue by dev-taewon-kim** [osamhack2021/ai_web_RISKOUT_BTS#98]
종종 발생하는 버그인데 도커 빌드하면 다음과 같은 버그가 발생합니다.

```
Creating nlp_nlptools_1 ... done
Attaching to nlp_nlptools_1
nlptools_1  | [2021-10-04 05:32:25 +0000] [1] [INFO] Starting gunicorn 20.1.0
nlptools_1  | [2021-10-04 05:32:25 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
nlptools_1  | [2021-10-04 05:32:25 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
nlptools_1  | [2021-10-04 05:32:25 +0000] [9] [INFO] Booting worker with pid: 9
nlptools_1  | [2021-10-04 05:32:25 +0000] [10] [INFO] Booting worker with pid: 10
[██████████████████████████████████████████████████][2021-10-04 05:32:59 +0000] [10] [ERROR] Exception in worker process
nlptools_1  | Traceback (most recent call last):
nlptools_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
nlptools_1  |     worker.init_process()
nlptools_1  |   File "/usr/local/lib/python3.7/site-packages/uvicorn/workers.py", line 66, in init_process
nlptools_1  |     super(UvicornWorker, self).init_process()
nlptools_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
nlptools_1  |     self.load_wsgi()
nlptools_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
nlptools_1  |     self.wsgi = self.app.wsgi()
nlptools_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
nlptools_1  |     self.callable = self.load()
nlptools_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
nlptools_1  |     return self.load_wsgiapp()
nlptools_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
nlptools_1  |     return util.import_app(self.app_uri)
nlptools_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
nlptools_1  |     mod = importlib.import_module(module)
nlptools_1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
nlptools_1  |     return _bootstrap._gcd_import(name[level:], package, level)
nlptools_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
nlptools_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
nlptools_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
nlptools_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
nlptools_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
nlptools_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
nlptools_1  |   File "/home/user/rest_api/application.py", line 33, in <module>
nlptools_1  |     kobart_summarizer = KorbartSummarizer(model_path=KOBARTSUM_MODEL_PATH)
nlptools_1  |   File "/home/user/riskout/summarization/summarizer.py", line 9, in __init__
nlptools_1  |     self.tokenizer = tokenizer()
nlptools_1  |   File "/usr/local/lib/python3.7/site-packages/kobart/utils.py", line 91, in get_kobart_tokenizer
nlptools_1  |     pad_token='<pad>', mask_token='<mask>')
nlptools_1  |   File "/usr/local/lib/python3.7/site-packages/transformers/tokenization_utils_fast.py", line 93, in __init__
nlptools_1  |     fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
nlptools_1  | Exception: stream did not contain valid UTF-8
nlptools_1  | [2021-10-04 05:32:59 +0000] [10] [INFO] Worker exiting (pid: 10)
nlptools_1  | 
nlptools_1  | [2021-10-04 05:33:00 +0000] [1] [WARNING] Worker with pid 9 was terminated due to signal 15
nlptools_1  | [2021-10-04 05:33:00 +0000] [1] [INFO] Shutting down: Master
nlptools_1  | [2021-10-04 05:33:00 +0000] [1] [INFO] Reason: Worker failed to boot.
nlp_nlptools_1 exited with code 3
```

보통 `docker-compose up` 한번 더 하면 없어지는 버그라 그냥 쓰고있는데

알아두셔야 할 것 같아서 이슈 남깁니다.

**Comment by dev-taewon-kim** [comment]
docker-compose.yml 에서 restart always 옵션을 넣어주는 것도 나쁘지 않은 해결 방안이라고 봅니다.

**Comment by dev-taewon-kim** [comment]
@playff 방금 테스트 해봤는데 restart always 넣으니 오류가 발생해도 알아서 restart 돼서 문제 해결됐습니다!
